### ISSUE TITLE
npm run dev throws an error

### ISSUE THREAD

**Issue by gnesher** [Zulko/eagle.js#43]
Just did a clean install (cloned repo, installed dependencies and ran `npm run dev`)
I'm getting the following error which isn't very helpful:
```
(node:4041) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.<anonymous> (/mnt/c/Users/Guy Nesher/Work/presentations/eaglejs-demo/node_modules/opn/index.js:83:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:4041) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:4041) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The demo does load and I can't tell exactly what's broken - but it's a little disconcerting

**Comment by yaodingyd** [comment]
This is a bug with `opn`. Since it's difficult to debug as it's relevant to node version and your OS, I recommend you look for `autoOpenBrowser` in `/config/index.js` and set it to false.

**Comment by yaodingyd** [comment]
will reopen for more details

**Comment by bala223344** [comment]
I was using ubuntu app in win10 and it couldn't launch the browser from within ubuntu..that was the issue..thanks

**Comment by yaodingyd** [comment]
@bala223344 this is an issue with `opn`. You have a better chance to solve this to open an issue there.
