### ISSUE TITLE
Use in vuepress?

### ISSUE THREAD

**Issue by bolerio** [Zulko/eagle.js#94]
I'm trying to use your vue-eagle-modal module in vuepress. I can build
and use it in development mode with 'npm run dev', but when I try to
build "production" version with 'npm run build', I get the following
error:

 WAIT  Extracting site metadata...
[2:17:14 AM] Compiling Client
[2:17:14 AM] Compiling Server
[2:17:27 AM] Compiled Server in 13s
[2:17:34 AM] Compiled Client in 20s
 WAIT  Rendering static HTML...
Rendering page: / FAIL  Error rendering /:
C:\Users\borislav.iordanov\code\gweb\website\node_modules\vue-eagle-modal\src\Plugin.js:5
import M from './components/List';
       ^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at C:\Users\borislav.iordanov\code\gweb\website\node_modules\vue-server-renderer\build.prod.js:1:77671
    at Object.module.exports.FUNC_ERROR_TEXT (webpack:/external
"vue-eagle-modal":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.<anonymous> (server-bundle.js:6678:33)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (server-bundle.js:3187:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at server-bundle.js:118:18
    at Object.<anonymous> (server-bundle.js:121:10)

**Comment by yaodingyd** [comment]
could you setup a repo?
